### PR TITLE
Fix archived

### LINKED ISSUE #192: Improve membership unarchivation
Archived User should have a button to request active membership status.
Group Leader should get a notifications about the request.
All Group Leader should be able to reactivate members.

### PR DESCRIPTION
**Pull request by SepsiLaszlo**
This PR closes #192 . 
Modifications:

- Group leader can rearchive archived members.
- Archived member can apply for reactivation.
- Membership model and controller tests migrated to rspec.

### CODE REVIEW

**Comment by OmTheTurtle** [comment]
Let's remove the .idea folder from this commit and add it to `.gitignore`

File: app/models/membership.rb [hunk 1]
```diff
@@ -78,13 +78,20 @@ def archive!
   end
 
   def unarchive!
+    destroy_newbie_post
```
Comment (OmTheTurtle) [inline app/models/membership.rb]: I don't think we need this here since only active members can be archived (if not, then it should be fixed).

Comment (SepsiLaszlo) [reply app/models/membership.rb]: When archived members apply to rejoin the group, they get newbie status so the group leader can see which members are waiting to be unarchived. So we need to destroy_newbie_post if  it's not nil. Or we can find a different approach for this.

File: spec/requests/membership_spec.rb [hunk 2]
```diff
@@ -0,0 +1,65 @@
+describe 'Membership' do
+  describe 'create' do
+
```
[the remark this answers is not in the document]
Comment (falusi94) [reply spec/requests/membership_spec.rb]: It’s also advised by rubocop by default

File: app/models/membership.rb (hunk 1 above)
Comment (OmTheTurtle) [reply app/models/membership.rb]: You're right, except they get the DEFAULT_POST_ID (which corresponds to 'feldolgozás alatt'. So I'd rename this method to `destroy_default_post`.

File: app/models/membership.rb [hunk 3]
```diff
@@ -78,13 +78,20 @@ def archive!
...
-    newbie_post = posts.find { |post| post.post_type.id == PostType::DEFAULT_POST_ID }
-    newbie_post.destroy
+    destroy_newbie_post
     post_types << PostType.find(PostType::NEW_MEMBER_ID)
   end
+
+  private
+
+  def destroy_newbie_post
+    newbie_post = posts.find { |post| post.post_type.id ==PostType::DEFAULT_POST_ID }
```
Comment (OmTheTurtle) [inline app/models/membership.rb]: Let's add an extra space after the `==`

File: spec/requests/membership_spec.rb [hunk 4]
```diff
@@ -0,0 +1,60 @@
+# frozen_string_literal: true
+
+describe Membership do
+  it 'delegation became false when archive' do
+    user = create(:user, :who_delegated)
+    membership = user.primary_membership
+
+    expect(membership.user.delegated).to be true
```
Comment (falusi94) [inline spec/requests/membership_spec.rb]: Usually every test has 4 phases:
- setup
- exercise
- verify
- teardown

In the current example, rspec and database cleaner take care about the last one. In my opinion this check doesn’t really have much added value before the exercise, we don’t want to verify the setup, but the exercise itself. It also adds some noise making harder to understand. I’d delete all the checks before the exercises and just keep the ones after it. What is your opinion?

File: spec/requests/memberships_controller_spec.rb [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+  it 'delegation became false when inactivate a group member who delegated that group' do
+    user = create(:user, :who_delegated)
+    membership = user.primary_membership
+    login_as(membership.group.leader.user)
+
+    expect(membership.user.delegated).to be true
+    expect(membership.user.primary_membership).to eql(membership)
+
+    Timecop.freeze do
+      membership.id #do we need this?
```
Comment (SepsiLaszlo) [inline spec/requests/memberships_controller_spec.rb]: I found this line in the original test, and I kept it. It doesn't do anything, should I remove it?

File: spec/requests/membership_spec.rb (hunk 4 above)
Comment (SepsiLaszlo) [reply spec/requests/membership_spec.rb]: I agree. It's a bit like we test the fixture, not our logic, which isn't a good practice in my opinion. I tried to keep the tests as close to the originals as possible, because I wasn't too confident with RSpec.  I'll remove it.

File: spec/requests/memberships_controller_spec.rb (hunk 5 above)
Comment (falusi94) [reply spec/requests/memberships_controller_spec.rb]: Yes please, it makes no sense.

File: test/factories/users.rb [hunk 6]
```diff
@@ -8,7 +8,7 @@
     sequence(:email) { |n| "sanyi_#{n}@example.org" }
     sequence(:cell_phone) { |n| "66677788#{n}" }
     sequence(:neptun) do |n|
-      random_character = (n + 48).chr
+      random_character = (n + 48).chr(Encoding::UTF_8)
```
Comment (SepsiLaszlo) [inline test/factories/users.rb]: Travis build failed, with the following output:
- Failure/Error: let(:user)        { create(:user) }
- ActiveRecord::StatementInvalid: PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0x80

I think this occurred because Integer.chr does not enforce encoding by default, only if encoding is specified as a parameter.

File: spec/requests/membership_spec.rb [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+      membership.accept!
+      membership.reload
+
+      expect(membership.newbie?).to be false
+      expect(membership.new_member?).to be true
+    end
+
+
+    it 'accepting membership notifies user' do
+      # membership= create(:membership, :newbie)
```
Comment (falusi94) [inline spec/requests/membership_spec.rb]: Please remove the comment.

File: spec/requests/memberships_controller_spec.rb [hunk 8]
```diff
@@ -0,0 +1,143 @@
+# frozen_string_literal: true
+
+describe MembershipsController do
+  describe '#create' do
+    context 'when user not a member' do
+      let(:user) { create(:user) }
+      let(:group) { create(:group) }
+      before(:each) { login_as(user) }
```
Comment (falusi94) [inline spec/requests/memberships_controller_spec.rb]: Here you have one `it` block in the `context` group, it's more advised to move these to there. Using `let`/`before` blocks can be very helpful, but in this case it just increases the complexity. I'd recommend
```ruby
it 'creates membership' do
  user  = create(:user)
  group = create(:group)
  login_as(user)
  ...
```

Other solution could be if you put the all of the `let`  blocks in the most outer `describe` block and you just define the differences in the `context` blocks if necessary, but in this case I recommend the first one.

Also the same applies to the further specs in this file.

File: test/factories/users.rb [hunk 9]
```diff
@@ -17,6 +17,7 @@
       svie_member_type { 'RENDESTAG' }
       after(:build) do |user|
         user.svie_primary_membership = create(:membership, user: user).id
+        user.primary_membership.group.update(issvie: true)
```
Comment (falusi94) [inline test/factories/users.rb]: Instead of updating the group here it'd nicer to add a `:for_svie_group` trait to the membership factory
```ruby
trait :for_svie_group
  association :group, issvie: true # or it can be added to the group factory as a trait and used from here
end
```
and here you can use
```ruby
user.svie_primary_membership = create(:membership, :for_svie_group, user: user).id
```

File: app/controllers/memberships_controller.rb [hunk 10]
```diff
@@ -35,4 +45,11 @@ def reactivate
   def accept
     Membership.find(params[:membership_id]).accept!
   end
+
+  private
+
+  def rejoin(membership)
```
Comment (OmTheTurtle) [inline app/controllers/memberships_controller.rb]: I think it'd be better to call this `reactivate`.

**Comment by SepsiLaszlo** [comment]
Chages that I did:
- Inactive members achived attribute is set to_end date when membership is archived
- Rename can_rejoin to  can_request_unarchivation?, rejoin to request_unarchivation, to be more descriptive.
- Some formatting. 

Changes in progress:
- Add tests for request_unarchivation
- Add test for memberships#accept
- Add tests for Memberships Controller to cover cases when user is not logged in, or not group_leader 

Questions:
- At the sprint planning, we spoke about inactive and archived users showing up in both tabs, but it is not the case in my local environment  
- memberships_controller_spec.rb is starting to get very long, should I divide it to smaller files?

File: spec/requests/memberships_controller_spec.rb (hunk 8 above)
Comment (SepsiLaszlo) [reply spec/requests/memberships_controller_spec.rb]: If I move all `let`/`before` blocks to the `it` block, should I remove the enclosing  `context` block? It doesn't do anything except appending a string to the tests name.

Comment (falusi94) [reply spec/requests/memberships_controller_spec.rb]: I’d say no. It helps the understanding and moving everything to the `it` block would only break the flow of the spec. Adding some blocks wouldn’t change the time necessary for running the tests, but can be very helpful when someone tries to understand it. For example:

```ruby
describe MembershipController do
  describe '#create' do
    context 'when the user is not member of the group' do
      it 'creates the membership' do
```

**Comment by SepsiLaszlo** [comment]
I made some bigger restructuring in `memberships_controller_spec.rb`. I didn't amended it to the last commit, so we can roll back easily if it went to the wrong direction. I will squash it if approved.

File: app/controllers/memberships_controller.rb [hunk 11]
```diff
@@ -7,13 +7,7 @@ def create
...
       redirect_back(fallback_location: group_path(@group))
     else
-      membership = @group.member?(current_user)
-      if membership && membership.can_request_unarchivation?
-        request_reactivation(membership)
-        redirect_back(fallback_location: group_path(@group))
-      else
-        forbidden_page
-      end
+      handle_unarchivation_request
```
Comment (SepsiLaszlo) [inline app/controllers/memberships_controller.rb:10]: I moved the logic to a private method, to reduce complexity in the `create` method.

File: spec/requests/memberships_controller_spec.rb [hunk 12]
```diff
@@ -1,130 +1,282 @@
 # frozen_string_literal: true
 
 describe MembershipsController do
+  shared_context 'current_user is the group leader' do
```
Comment (SepsiLaszlo) [inline spec/requests/memberships_controller_spec.rb:4]: I tried reduce nesting and complexity with shared_contexts to in this test file. Any thoughts on this?

File: spec/requests/memberships_controller_spec.rb [hunk 13]
```diff
@@ -1,130 +1,282 @@
...
+    end
+
+    context 'when membership is archived and current_user is member' do
+      include_context 'current_user is a member'
+      let(:membership) { create(:membership, :archived) }
+
+      it 'notifies the group leader' do
+        expect_any_instance_of(Membership).to receive(:notify).and_call_original
+
+        expect {
```
Comment (SepsiLaszlo) [inline spec/requests/memberships_controller_spec.rb:54]: The group leader already had one notification from creating the membership. Expecting eq(2) on the `notifications.count` seemed  weird so I used this.

File: spec/requests/memberships_controller_spec.rb (hunk 12 above)
Comment (falusi94) [reply spec/requests/memberships_controller_spec.rb:4]: I forgot to add to the meeting, so I do it here. I didn't know about this feature of rspec, I like the way it groups the setup for the test, but on the other hand I feel it can increase the complexity. In this actual case I think it can be avoided with the refactor.

**Comment by SepsiLaszlo** [comment]
Some changes were in the wrong commit, I moved them to the correct one.
